// <auto-generated />
using System;
using GestaoResiduosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GestaoResiduosApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241203102959_AddRecipientes")]
    partial class AddRecipientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoResiduosApi.Models.AgendamentoModel", b =>
                {
                    b.Property<long>("IdAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_agendamento");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAgendamento"));

                    b.Property<DateTime>("DtAgendamento")
                        .HasColumnType("date")
                        .HasColumnName("dt_agendamento");

                    b.Property<string>("StatusAgendamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status_agendamento");

                    b.Property<long>("T_ROTA_id_rota")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("IdAgendamento");

                    b.HasIndex("T_ROTA_id_rota");

                    b.ToTable("t_agendamento", (string)null);
                });

            modelBuilder.Entity("GestaoResiduosApi.Models.CaminhaoModel", b =>
                {
                    b.Property<long>("IdCaminhao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_caminhao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCaminhao"));

                    b.Property<long>("Capacidade")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ds_capacidade");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ds_placa");

                    b.HasKey("IdCaminhao");

                    b.ToTable("t_caminhao", (string)null);
                });

            modelBuilder.Entity("GestaoResiduosApi.Models.EmergenciaModel", b =>
                {
                    b.Property<long>("IdEmergencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_emergencia");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEmergencia"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ds_emergencia");

                    b.Property<DateTime>("DtEmergencia")
                        .HasColumnType("date")
                        .HasColumnName("dt_emergencia");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.Property<long>("T_CAMINHAO_ID_CAMINHAO")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("T_RECIPIENTE_ID_RECIPIENTE")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("IdEmergencia");

                    b.HasIndex("T_CAMINHAO_ID_CAMINHAO");

                    b.HasIndex("T_RECIPIENTE_ID_RECIPIENTE");

                    b.ToTable("t_emergencia", (string)null);
                });

            modelBuilder.Entity("GestaoResiduosApi.Models.RecipienteModel", b =>
                {
                    b.Property<long>("IdRecipiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_recipiente");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRecipiente"));

                    b.Property<long>("AtualNivel")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("atual_nvl");

                    b.Property<long>("Latitude")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("latitude_recip");

                    b.Property<long>("Longitude")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("longitude_recip");

                    b.Property<long>("MaxCapacidade")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("max_capacidade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("date")
                        .HasColumnName("ultima_att");

                    b.HasKey("IdRecipiente");

                    b.ToTable("t_recipiente", (string)null);
                });

            modelBuilder.Entity("GestaoResiduosApi.Models.RotaModel", b =>
                {
                    b.Property<long>("IdRota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_rota");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdRota"));

                    b.Property<DateTime>("DtRota")
                        .HasColumnType("date")
                        .HasColumnName("dt_rota");

                    b.Property<long>("T_CAMINHAO_id_caminhao")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("T_RECIPIENTE_id_recipiente")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("IdRota");

                    b.HasIndex("T_CAMINHAO_id_caminhao");

                    b.HasIndex("T_RECIPIENTE_id_recipiente");

                    b.ToTable("t_rota", (string)null);
                });

            modelBuilder.Entity("GestaoResiduosApi.Models.AgendamentoModel", b =>
                {
                    b.HasOne("GestaoResiduosApi.Models.RotaModel", "Rota")
                        .WithMany()
                        .HasForeignKey("T_ROTA_id_rota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("GestaoResiduosApi.Models.EmergenciaModel", b =>
                {
                    b.HasOne("GestaoResiduosApi.Models.CaminhaoModel", "Caminhao")
                        .WithMany()
                        .HasForeignKey("T_CAMINHAO_ID_CAMINHAO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoResiduosApi.Models.RecipienteModel", "Recipiente")
                        .WithMany()
                        .HasForeignKey("T_RECIPIENTE_ID_RECIPIENTE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caminhao");

                    b.Navigation("Recipiente");
                });

            modelBuilder.Entity("GestaoResiduosApi.Models.RotaModel", b =>
                {
                    b.HasOne("GestaoResiduosApi.Models.CaminhaoModel", "Caminhao")
                        .WithMany()
                        .HasForeignKey("T_CAMINHAO_id_caminhao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoResiduosApi.Models.RecipienteModel", "Recipiente")
                        .WithMany()
                        .HasForeignKey("T_RECIPIENTE_id_recipiente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caminhao");

                    b.Navigation("Recipiente");
                });
#pragma warning restore 612, 618
        }
    }
}
